// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"time"
)

// Defines values for ConnectionKind.
const (
	ConnectionKindAnthropic  ConnectionKind = "anthropic"
	ConnectionKindFakevendor ConnectionKind = "fakevendor"
	ConnectionKindOpenai     ConnectionKind = "openai"
)

// Valid indicates whether the value is a known member of the ConnectionKind enum.
func (e ConnectionKind) Valid() bool {
	switch e {
	case ConnectionKindAnthropic:
		return true
	case ConnectionKindFakevendor:
		return true
	case ConnectionKindOpenai:
		return true
	default:
		return false
	}
}

// Defines values for ConnectionStatus.
const (
	Degraded  ConnectionStatus = "degraded"
	Failing   ConnectionStatus = "failing"
	Healthy   ConnectionStatus = "healthy"
	NeedsAuth ConnectionStatus = "needs_auth"
	Paused    ConnectionStatus = "paused"
)

// Valid indicates whether the value is a known member of the ConnectionStatus enum.
func (e ConnectionStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Failing:
		return true
	case Healthy:
		return true
	case NeedsAuth:
		return true
	case Paused:
		return true
	default:
		return false
	}
}

// Defines values for ConnectionCreateKind.
const (
	ConnectionCreateKindAnthropic  ConnectionCreateKind = "anthropic"
	ConnectionCreateKindFakevendor ConnectionCreateKind = "fakevendor"
	ConnectionCreateKindOpenai     ConnectionCreateKind = "openai"
)

// Valid indicates whether the value is a known member of the ConnectionCreateKind enum.
func (e ConnectionCreateKind) Valid() bool {
	switch e {
	case ConnectionCreateKindAnthropic:
		return true
	case ConnectionCreateKindFakevendor:
		return true
	case ConnectionCreateKindOpenai:
		return true
	default:
		return false
	}
}

// Defines values for EventStatus.
const (
	EventStatusFailed    EventStatus = "failed"
	EventStatusPending   EventStatus = "pending"
	EventStatusProcessed EventStatus = "processed"
)

// Valid indicates whether the value is a known member of the EventStatus enum.
func (e EventStatus) Valid() bool {
	switch e {
	case EventStatusFailed:
		return true
	case EventStatusPending:
		return true
	case EventStatusProcessed:
		return true
	default:
		return false
	}
}

// Defines values for SyncJobKind.
const (
	Backfill  SyncJobKind = "backfill"
	Reconnect SyncJobKind = "reconnect"
	Scheduled SyncJobKind = "scheduled"
)

// Valid indicates whether the value is a known member of the SyncJobKind enum.
func (e SyncJobKind) Valid() bool {
	switch e {
	case Backfill:
		return true
	case Reconnect:
		return true
	case Scheduled:
		return true
	default:
		return false
	}
}

// Defines values for SyncJobStatus.
const (
	SyncJobStatusCancelled   SyncJobStatus = "cancelled"
	SyncJobStatusFailed      SyncJobStatus = "failed"
	SyncJobStatusQuarantined SyncJobStatus = "quarantined"
	SyncJobStatusQueued      SyncJobStatus = "queued"
	SyncJobStatusRunning     SyncJobStatus = "running"
	SyncJobStatusSucceeded   SyncJobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the SyncJobStatus enum.
func (e SyncJobStatus) Valid() bool {
	switch e {
	case SyncJobStatusCancelled:
		return true
	case SyncJobStatusFailed:
		return true
	case SyncJobStatusQuarantined:
		return true
	case SyncJobStatusQueued:
		return true
	case SyncJobStatusRunning:
		return true
	case SyncJobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for GetV1EventsParamsStatus.
const (
	GetV1EventsParamsStatusAll       GetV1EventsParamsStatus = "all"
	GetV1EventsParamsStatusFailed    GetV1EventsParamsStatus = "failed"
	GetV1EventsParamsStatusPending   GetV1EventsParamsStatus = "pending"
	GetV1EventsParamsStatusProcessed GetV1EventsParamsStatus = "processed"
)

// Valid indicates whether the value is a known member of the GetV1EventsParamsStatus enum.
func (e GetV1EventsParamsStatus) Valid() bool {
	switch e {
	case GetV1EventsParamsStatusAll:
		return true
	case GetV1EventsParamsStatusFailed:
		return true
	case GetV1EventsParamsStatusPending:
		return true
	case GetV1EventsParamsStatusProcessed:
		return true
	default:
		return false
	}
}

// Defines values for GetV1EventsStreamParamsStatus.
const (
	GetV1EventsStreamParamsStatusAll       GetV1EventsStreamParamsStatus = "all"
	GetV1EventsStreamParamsStatusFailed    GetV1EventsStreamParamsStatus = "failed"
	GetV1EventsStreamParamsStatusPending   GetV1EventsStreamParamsStatus = "pending"
	GetV1EventsStreamParamsStatusProcessed GetV1EventsStreamParamsStatus = "processed"
)

// Valid indicates whether the value is a known member of the GetV1EventsStreamParamsStatus enum.
func (e GetV1EventsStreamParamsStatus) Valid() bool {
	switch e {
	case GetV1EventsStreamParamsStatusAll:
		return true
	case GetV1EventsStreamParamsStatusFailed:
		return true
	case GetV1EventsStreamParamsStatusPending:
		return true
	case GetV1EventsStreamParamsStatusProcessed:
		return true
	default:
		return false
	}
}

// BackfillRequest defines model for BackfillRequest.
type BackfillRequest struct {
	End   time.Time `json:"end"`
	Start time.Time `json:"start"`
}

// Connection defines model for Connection.
type Connection struct {
	Credential       *Credential      `json:"credential,omitempty"`
	Id               string           `json:"id"`
	Kind             ConnectionKind   `json:"kind"`
	LastErrorAt      *time.Time       `json:"lastErrorAt,omitempty"`
	LastSuccessAt    *time.Time       `json:"lastSuccessAt,omitempty"`
	Name             string           `json:"name"`
	Status           ConnectionStatus `json:"status"`
	StatusReasonCode *string          `json:"statusReasonCode,omitempty"`
}

// ConnectionKind defines model for Connection.Kind.
type ConnectionKind string

// ConnectionStatus defines model for Connection.Status.
type ConnectionStatus string

// ConnectionCreate defines model for ConnectionCreate.
type ConnectionCreate struct {
	ExpiresAt *time.Time           `json:"expiresAt,omitempty"`
	Kind      ConnectionCreateKind `json:"kind"`
	Name      string               `json:"name"`

	// Secret Sent once. Stored as an encrypted envelope, never returned.
	Secret string `json:"secret"`
}

// ConnectionCreateKind defines model for ConnectionCreate.Kind.
type ConnectionCreateKind string

// ConnectionPatch defines model for ConnectionPatch.
type ConnectionPatch struct {
	Name   *string `json:"name,omitempty"`
	Paused *bool   `json:"paused,omitempty"`
}

// CostPage defines model for CostPage.
type CostPage struct {
	Costs      []CostRow `json:"costs"`
	NextCursor *string   `json:"nextCursor,omitempty"`
	Total      int       `json:"total"`
}

// CostRow defines model for CostRow.
type CostRow struct {
	BatchId           *string    `json:"batchId,omitempty"`
	BilledCost        string     `json:"billedCost"`
	BillingAccountId  *string    `json:"billingAccountId,omitempty"`
	BillingCurrency   *string    `json:"billingCurrency,omitempty"`
	ChargeCategory    *string    `json:"chargeCategory,omitempty"`
	ChargePeriodEnd   time.Time  `json:"chargePeriodEnd"`
	ChargePeriodStart time.Time  `json:"chargePeriodStart"`
	ConnectionId      string     `json:"connectionId"`
	EffectiveCost     string     `json:"effectiveCost"`
	Id                string     `json:"id"`
	IngestedAt        *time.Time `json:"ingestedAt,omitempty"`
	JobId             *string    `json:"jobId,omitempty"`
	ProviderName      string     `json:"providerName"`
	ResourceId        *string    `json:"resourceId,omitempty"`
	ServiceCategory   *string    `json:"serviceCategory,omitempty"`
	ServiceName       string     `json:"serviceName"`
	SkuId             *string    `json:"skuId,omitempty"`
	SourceRecordId    *string    `json:"sourceRecordId,omitempty"`
	UsageQuantity     *string    `json:"usageQuantity,omitempty"`
	UsageUnit         *string    `json:"usageUnit,omitempty"`
}

// Credential defines model for Credential.
type Credential struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Fingerprint SHA-256 of the secret. The secret itself is never returned.
	Fingerprint string `json:"fingerprint"`
}

// CredentialRotate defines model for CredentialRotate.
type CredentialRotate struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Secret    string     `json:"secret"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Event defines model for Event.
type Event struct {
	// ConnectionId Present when the event is tied to a vendor connection.
	ConnectionId  *string     `json:"connectionId,omitempty"`
	CorrelationId string      `json:"correlationId"`
	Id            string      `json:"id"`
	OccurredAt    time.Time   `json:"occurredAt"`
	Source        string      `json:"source"`
	Status        EventStatus `json:"status"`
	Type          string      `json:"type"`
}

// EventStatus defines model for Event.Status.
type EventStatus string

// EventPage defines model for EventPage.
type EventPage struct {
	Events []Event `json:"events"`

	// NextCursor Present when another page is available.
	NextCursor *string `json:"nextCursor,omitempty"`

	// Total Matching events, not just the current page.
	Total int `json:"total"`
}

// Problem RFC 9457 problem details. code matches the shared error catalog when the failure is a known one.
type Problem struct {
	Action    *string `json:"action,omitempty"`
	Code      *string `json:"code,omitempty"`
	Detail    *string `json:"detail,omitempty"`
	Retryable *bool   `json:"retryable,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// SyncJob defines model for SyncJob.
type SyncJob struct {
	Attempt      *int          `json:"attempt,omitempty"`
	ConnectionId string        `json:"connectionId"`
	ErrorCode    *string       `json:"errorCode,omitempty"`
	ErrorDetail  *string       `json:"errorDetail,omitempty"`
	Id           string        `json:"id"`
	Kind         SyncJobKind   `json:"kind"`
	MaxAttempts  *int          `json:"maxAttempts,omitempty"`
	Status       SyncJobStatus `json:"status"`
	WindowEnd    time.Time     `json:"windowEnd"`
	WindowStart  time.Time     `json:"windowStart"`
	WorkspaceId  *string       `json:"workspaceId,omitempty"`
}

// SyncJobKind defines model for SyncJob.Kind.
type SyncJobKind string

// SyncJobStatus defines model for SyncJob.Status.
type SyncJobStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// PostV1ConnectionsParams defines parameters for PostV1Connections.
type PostV1ConnectionsParams struct {
	// IdempotencyKey On a mutating request, a retry with the same key and body returns the stored response. The same key with a different body is rejected.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PatchV1ConnectionsIdParams defines parameters for PatchV1ConnectionsId.
type PatchV1ConnectionsIdParams struct {
	// IdempotencyKey On a mutating request, a retry with the same key and body returns the stored response. The same key with a different body is rejected.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostV1ConnectionsIdBackfillParams defines parameters for PostV1ConnectionsIdBackfill.
type PostV1ConnectionsIdBackfillParams struct {
	// IdempotencyKey On a mutating request, a retry with the same key and body returns the stored response. The same key with a different body is rejected.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostV1ConnectionsIdRotateParams defines parameters for PostV1ConnectionsIdRotate.
type PostV1ConnectionsIdRotateParams struct {
	// IdempotencyKey On a mutating request, a retry with the same key and body returns the stored response. The same key with a different body is rejected.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PostV1ConnectionsIdVerifyParams defines parameters for PostV1ConnectionsIdVerify.
type PostV1ConnectionsIdVerifyParams struct {
	// IdempotencyKey On a mutating request, a retry with the same key and body returns the stored response. The same key with a different body is rejected.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetV1CostsParams defines parameters for GetV1Costs.
type GetV1CostsParams struct {
	ConnectionId *string `form:"connection_id,omitempty" json:"connection_id,omitempty"`

	// Start RFC3339 lower bound on charge period end.
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`

	// End RFC3339 upper bound on charge period start.
	End    *time.Time `form:"end,omitempty" json:"end,omitempty"`
	Cursor *string    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetV1EventsParams defines parameters for GetV1Events.
type GetV1EventsParams struct {
	// Q Case-insensitive match against event ID, source, type, or correlation ID.
	Q      *string                  `form:"q,omitempty" json:"q,omitempty"`
	Status *GetV1EventsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque keyset from a previous page. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Defaults to 50. Maximum 100.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// ConnectionId Restrict the feed to one connection. Empty for the demo fixtures.
	ConnectionId *string `form:"connection_id,omitempty" json:"connection_id,omitempty"`
}

// GetV1EventsParamsStatus defines parameters for GetV1Events.
type GetV1EventsParamsStatus string

// GetV1EventsStreamParams defines parameters for GetV1EventsStream.
type GetV1EventsStreamParams struct {
	// Q Case-insensitive match against event ID, source, type, or correlation ID.
	Q            *string                        `form:"q,omitempty" json:"q,omitempty"`
	Status       *GetV1EventsStreamParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Cursor       *string                        `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit        *int                           `form:"limit,omitempty" json:"limit,omitempty"`
	ConnectionId *string                        `form:"connection_id,omitempty" json:"connection_id,omitempty"`
}

// GetV1EventsStreamParamsStatus defines parameters for GetV1EventsStream.
type GetV1EventsStreamParamsStatus string

// PostV1ConnectionsJSONRequestBody defines body for PostV1Connections for application/json ContentType.
type PostV1ConnectionsJSONRequestBody = ConnectionCreate

// PatchV1ConnectionsIdJSONRequestBody defines body for PatchV1ConnectionsId for application/json ContentType.
type PatchV1ConnectionsIdJSONRequestBody = ConnectionPatch

// PostV1ConnectionsIdBackfillJSONRequestBody defines body for PostV1ConnectionsIdBackfill for application/json ContentType.
type PostV1ConnectionsIdBackfillJSONRequestBody = BackfillRequest

// PostV1ConnectionsIdRotateJSONRequestBody defines body for PostV1ConnectionsIdRotate for application/json ContentType.
type PostV1ConnectionsIdRotateJSONRequestBody = CredentialRotate
