// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"time"
)

// Defines values for EventStatus.
const (
	EventStatusFailed    EventStatus = "failed"
	EventStatusPending   EventStatus = "pending"
	EventStatusProcessed EventStatus = "processed"
)

// Valid indicates whether the value is a known member of the EventStatus enum.
func (e EventStatus) Valid() bool {
	switch e {
	case EventStatusFailed:
		return true
	case EventStatusPending:
		return true
	case EventStatusProcessed:
		return true
	default:
		return false
	}
}

// Defines values for GetV1EventsParamsStatus.
const (
	GetV1EventsParamsStatusAll       GetV1EventsParamsStatus = "all"
	GetV1EventsParamsStatusFailed    GetV1EventsParamsStatus = "failed"
	GetV1EventsParamsStatusPending   GetV1EventsParamsStatus = "pending"
	GetV1EventsParamsStatusProcessed GetV1EventsParamsStatus = "processed"
)

// Valid indicates whether the value is a known member of the GetV1EventsParamsStatus enum.
func (e GetV1EventsParamsStatus) Valid() bool {
	switch e {
	case GetV1EventsParamsStatusAll:
		return true
	case GetV1EventsParamsStatusFailed:
		return true
	case GetV1EventsParamsStatusPending:
		return true
	case GetV1EventsParamsStatusProcessed:
		return true
	default:
		return false
	}
}

// Defines values for GetV1EventsStreamParamsStatus.
const (
	GetV1EventsStreamParamsStatusAll       GetV1EventsStreamParamsStatus = "all"
	GetV1EventsStreamParamsStatusFailed    GetV1EventsStreamParamsStatus = "failed"
	GetV1EventsStreamParamsStatusPending   GetV1EventsStreamParamsStatus = "pending"
	GetV1EventsStreamParamsStatusProcessed GetV1EventsStreamParamsStatus = "processed"
)

// Valid indicates whether the value is a known member of the GetV1EventsStreamParamsStatus enum.
func (e GetV1EventsStreamParamsStatus) Valid() bool {
	switch e {
	case GetV1EventsStreamParamsStatusAll:
		return true
	case GetV1EventsStreamParamsStatusFailed:
		return true
	case GetV1EventsStreamParamsStatusPending:
		return true
	case GetV1EventsStreamParamsStatusProcessed:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Event defines model for Event.
type Event struct {
	CorrelationId string      `json:"correlationId"`
	Id            string      `json:"id"`
	OccurredAt    time.Time   `json:"occurredAt"`
	Source        string      `json:"source"`
	Status        EventStatus `json:"status"`
	Type          string      `json:"type"`
}

// EventStatus defines model for Event.Status.
type EventStatus string

// EventPage defines model for EventPage.
type EventPage struct {
	Events []Event `json:"events"`

	// NextCursor Present when another page is available.
	NextCursor *string `json:"nextCursor,omitempty"`

	// Total Matching events, not just the current page.
	Total int `json:"total"`
}

// Problem RFC 9457 problem details. code matches the shared error catalog when the failure is a known one.
type Problem struct {
	Action    *string `json:"action,omitempty"`
	Code      *string `json:"code,omitempty"`
	Detail    *string `json:"detail,omitempty"`
	Retryable *bool   `json:"retryable,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// GetV1EventsParams defines parameters for GetV1Events.
type GetV1EventsParams struct {
	// Q Case-insensitive match against event ID, source, type, or correlation ID.
	Q      *string                  `form:"q,omitempty" json:"q,omitempty"`
	Status *GetV1EventsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque keyset from a previous page. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Defaults to 50. Maximum 100.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// ConnectionId Restrict the feed to one connection. Empty for the demo fixtures.
	ConnectionId *string `form:"connection_id,omitempty" json:"connection_id,omitempty"`
}

// GetV1EventsParamsStatus defines parameters for GetV1Events.
type GetV1EventsParamsStatus string

// GetV1EventsStreamParams defines parameters for GetV1EventsStream.
type GetV1EventsStreamParams struct {
	// Q Case-insensitive match against event ID, source, type, or correlation ID.
	Q            *string                        `form:"q,omitempty" json:"q,omitempty"`
	Status       *GetV1EventsStreamParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Cursor       *string                        `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit        *int                           `form:"limit,omitempty" json:"limit,omitempty"`
	ConnectionId *string                        `form:"connection_id,omitempty" json:"connection_id,omitempty"`
}

// GetV1EventsStreamParamsStatus defines parameters for GetV1EventsStream.
type GetV1EventsStreamParamsStatus string
